apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
  - image: mongo:4
    name: mongodb
    volumeMounts:
    - name: shared-storage
      mountPath: /data/shared
  - image: nginx
    name: nginx
    volumeMounts:
    - name: shared-storage
      mountPath: /data/shared
  volumes:
  - name: shared-storage
    emptyDir: {}